FROM node:20-alpine

WORKDIR /app

# Dependências
COPY Front/package*.json ./
RUN npm install --legacy-peer-deps

# Código
COPY Front/ ./

EXPOSE 4200

# Serve a aplicação Angular
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll=2000"]
